version: '3.8'
services:
  db:
      image: 'postgres:latest'
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./main
    ports:
      -  ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
  